### PR TITLE
Trace and optional formatting

### LINKED ISSUE #4: Integrate optional trace in order to easily identify where logs are being outputted
### Specification

Sometimes we get logging messages where we don't know where they came from, and it would be nice to know how the code arrived at that execution point.

The `console.trace()` can immediately show a trace of where you are.

```
Trace
    at abc (/home/cmcdragonkai/Projects/TypeScript-Demo-Lib/trace.ts:4:11)
    at Object.<anonymous> (/home/cmcdragonkai/Projects/TypeScript-Demo-Lib/trace.ts:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/home/cmcdragonkai/Projects/TypeScript-Demo-Lib/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/cmcdragonkai/Projects/TypeScript-Demo-Lib/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at phase4 (/home/cmcdragonkai/Projects/TypeScript-Demo-Lib/node_modules/ts-node/src/bin.ts:567:12)
```

But it prints to stdout, and we would want it as a variable. The `Error.stack` property seems to be something we can use. https://stackoverflow.com/a/36172532/582917

```
function getStackTrace () {
    let stack = new Error().stack || '';
    stack = stack.split('\n').map(function (line) { return line.trim(); });
    return stack.splice(stack[0] == 'Error' ? 2 : 1);
}

getStackTrace()[2]; // get stack trace info 2 levels-deep
```

This trace string can then be part of the logged out information, which would make it easier to find out where a particular log message is occurring.

Adding it into the formatting however can make logs VERY noisy. Which would rely on #3 to help decipher.

Additionally we can add "custom formatting" override to the logging method `logger.info` which can help us to interactive debugging.

Note that enabling traces would be quite expensive.

### Tasks

1. Add in additional `trace` keyword
2. Consider that traces are multi-line strings, but loggers are supposed to output a single line
3. Therefore these things will be part of whether we have human readable logging or structured logging
4. Add the ability to override the format in the `logger.info` and related methods

### PR DESCRIPTION
**Pull request by tegefaulkes**
### Description

This adds a `trace` key to the formatter. this when added to the end of the format will print out a error like stack trace in the log message. Note that this breaks the one message per line log convention and should only be used for debugging.

This PR also adds an optional format override to a log message. So now you can change the log formmat on a per-message basis. You can do this by doing.
```ts
logger.info('message', formatter.format`new format ${formatter.msg}${formatter.trace}`);
```

### Issues Fixed

* Fixes #4

### Tasks

- [x] 1. add a `trace` key to the formatter.
- [x] 2. add an optional format override to each logger method.

### Final checklist

* [x] Domain specific tests
* [x] Full tests
* [x] Updated inline-comment documentation
* [x] Lint fixed
* [x] Squash and rebased
* [x] Sanity check the final build

### CODE REVIEW

File: src/Handler.ts [hunk 1]
```diff
@@ -13,8 +13,8 @@ abstract class Handler {
     this.formatter = formatter;
   }
 
-  public handle(record: LogRecord): void {
-    const output = this.format(record);
+  public handle(record: LogRecord, format?: LogFormatter): void {
+    const output = format == null ? this.format(record) : format(record);
```
Comment (CMCDragonkai) [inline src/Handler.ts:17]: Should this be `(format == null) ? ... : ...`? I thought the linter would change this.

Comment (CMCDragonkai) [reply src/Handler.ts:17]: Also I prefer checking for positives first. Like `(format != null) ? format(record) : this.format(record)`. Also defaulting should usually be at the right side.

File: src/formatting.ts [hunk 2]
```diff
@@ -32,6 +33,13 @@ function format(
         result += record.msg;
       } else if (value === level) {
         result += levelToString(record.level);
+      } else if (value === trace) {
+        const errorStack = new Error().stack ?? '';
```
Comment (CMCDragonkai) [inline src/formatting.ts:37]: I think we can do something simpler here, if the `stack` is `== null`, then we just don't do anything, and substitute `${trace}` for `''`. So we should do early termination here.

File: src/formatting.ts [hunk 3]
```diff
@@ -32,6 +33,13 @@ function format(
...
+        const splitErrorStack = errorStack.split('\n');
+        const position =
+          splitErrorStack.findIndex((value) => /Logger\.log/.test(value)) ?? 0;
+        const formattedStack = splitErrorStack.splice(position + 1).join('\n');
```
Comment (CMCDragonkai) [inline src/formatting.ts:41]: Can you show us an example of this log message? I'd like to get rid of the first 1 or 2 lines since the stack should really start where the `logger.info()` is made, and not start here.

File: src/Handler.ts (hunk 1 above)
Comment (tegefaulkes) [reply src/Handler.ts:17]: Looks like the linting converts `(format != null)` to `format != null`. But otherwise I can flip it around.

File: src/formatting.ts (hunk 3 above)
Comment (tegefaulkes) [reply src/formatting.ts:41]: Here is an example
```
2020-01-01T00:00:00.000Z:DEBUG MESSAGE
    at Logger.debug (/home/faulkes/matrixcode/polykey/js-logger/src/Logger.ts:78:10)
    at Object.<anonymous> (/home/faulkes/matrixcode/polykey/js-logger/tests/index.test.ts:111:12)
    at Promise.then.completed (/home/faulkes/matrixcode/polykey/js-logger/node_modules/jest-circus/build/utils.js:391:28)
    at new Promise (<anonymous>)
    at callAsyncCircusFn (/home/faulkes/matrixcode/polykey/js-logger/node_modules/jest-circus/build/utils.js:316:10)"
```

The line pointing to where the message is is the 3rd line containing `at Object.<anonymous> (/home/faulkes/matrixcode/polykey/js-logger/tests/index.test.ts:111:12)`. I kept the line `Logger.debug` here to show what kind of debug message it was but we can skip that one as well.

Comment (CMCDragonkai) [reply src/formatting.ts]: Yea I think the `Logger.debug` is not necessary, since we already know this simply through the `${level}` symbol. So we should start with just:

```
    at Object.<anonymous> (/home/faulkes/matrixcode/polykey/js-logger/tests/index.test.ts:111:12)
```

File: src/Handler.ts (hunk 1 above)
Comment (CMCDragonkai) [reply src/Handler.ts]: Yea please flip it around then resolve.

File: src/formatting.ts (hunk 3 above)
Comment (tegefaulkes) [reply src/formatting.ts]: Fixed.

**Comment by CMCDragonkai** [comment]
@emmacasolin great this will be useful for debugging spurious logs now!

**Comment by tegefaulkes** [comment]
Weird. It doesn't get rid of the first 2 lines, it removes about 6 of them. It's different if you set the format for the logger of use the override method so I had to filter for an expected line. since it's showing the trace starting from the same point I think that's working. But if the trace is limited to 10 line and we cut off most of them then maybe that's why we're getting a very short trace there. I'll look into it.

**Comment by tegefaulkes** [comment]
Yeah, by default the stack trace is limited to 10 lines. since we're cutting them off we only get 2 lines at the end in this case. There is a fix for this but it's really not ideal. You can change how many lines you get in the stack trace with `Error.stackTraceLimit = 100;` but it will affect all errors. Also it's not standard so I can't say it will work consistently or at all on all platforms.

I can quicky set the `stackTraceLimit` to `stackTraceLimit + 8` and then set it back after getting the stack. But we can have a concurrency issue where other errors feel the affects of this. But over all the consequence of this is minimal. We may not even notice it.

**Comment by CMCDragonkai** [comment]
Using both `Error.captureStackTrace` we can actually do this a little more elegantly:

```
class C {

  public log () {
    return format();
  }

  public info () {
    return this.log();
  }

}

function format () {
  const e = {} as { stack: string };
  Error.captureStackTrace(e, C.prototype.log);
  return e.stack;
}

async function main () {
  const c = new C;
  console.log(c.info());
}

main();
```

The resulting function assigns the stack string to the arbitrary object `e`.

The `C.prototype.log` can be `Logger.prototype.log`.

This still gives us:

```
Error
    at C.info (/home/cmcdragonkai/Projects/js-db/test-errors.ts:8:17)
    at main (/home/cmcdragonkai/Projects/js-db/test-errors.ts:21:17)
    at Object.<anonymous> (/home/cmcdragonkai/Projects/js-db/test-errors.ts:24:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/home/cmcdragonkai/Projects/js-db/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/home/cmcdragonkai/Projects/js-db/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
```

In which case you would need to splice out the remaining `C.info`.

To maintain the default stack limit, increment the `Error.stackTraceLimit`, then decrement it afterwards.

Resulting in:

```
class C {

  public log () {
    return format();
  }

  public info () {
    return this.log();
  }

}

function format () {
  const e = {} as { stack: string };
  Error.stackTraceLimit++;
  Error.captureStackTrace(e, C.prototype.log);
  Error.stackTraceLimit--;
  return e.stack;
}

async function main () {
  const c = new C;
  console.log(c.info());
}

main();
```

This makes use of V8 API. In fact both are not Ecmascript standards atm. Which means it is limited to nodejs and chrome based browsers.

If we want to make js-loggers generic, the `trace` keyword would have to be somewhat limited to v8 based systems here. In which case if `captureStackTrace` or `stackTraceLimit` properties do not exist on `Error`, then you are limited to just doing `new Error().stack ?? ''`. @tegefaulkes please add a check to do so.
